[deps]
AtomsBase = "a963bdd2-2df7-4f54-a1ee-49d51e6be12a"
InteratomicPotentials = "a9efe35a-c65d-452d-b8a8-82646cd5cb04"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"
Unitful = "1986cc42-f94f-5a68-af5c-568840ba703d"
UnitfulAtomic = "a7773ee8-282e-5fa2-be4e-bd808c38a91a"
